-- Minimal production-shaped baseline for compiling M5-001 in disposable PostgreSQL CI.
-- This is intentionally not a production schema authority; it only provides objects referenced by the migration.

create table public.memory_review_queue_items (
  id uuid primary key,
  user_id uuid not null,
  namespace text not null,
  status text not null,
  candidate_type text not null default 'memory',
  normalized_text text not null default '',
  evidence_snapshot jsonb not null default '{}'::jsonb,
  sensitivity_snapshot jsonb not null default '{}'::jsonb,
  namespace_snapshot jsonb not null default '{}'::jsonb,
  source_metadata jsonb not null default '{}'::jsonb,
  audit_metadata jsonb not null default '{}'::jsonb,
  append_only boolean not null default true,
  proposed_operation text not null default 'append',
  requires_review boolean not null default true,
  source_ref text,
  request_hash text,
  fingerprint text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  archived_at timestamptz,
  persisted_at timestamptz,
  persistence_status text,
  persistence_execution_metadata jsonb not null default '{}'::jsonb
);

create table public.memory_review_queue_decisions (
  id uuid primary key,
  review_item_id uuid not null,
  user_id uuid not null,
  namespace text not null,
  action text not null default 'approve',
  from_status text not null default 'pending_review',
  to_status text not null,
  reviewer_context jsonb not null default '{}'::jsonb,
  decision_metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table public.memory_items (
  id uuid primary key,
  user_id uuid not null,
  namespace text not null,
  memory_type text not null,
  title text not null,
  body text not null,
  strength text not null default 'medium',
  confidence numeric(5,4) not null default 0.5000,
  canon_status text not null default 'draft',
  source_summary text,
  metadata jsonb not null default '{}'::jsonb,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  project_id uuid,
  record_type text,
  content_hash text,
  idempotency_key text,
  ingestion_version integer not null default 1,
  source_type text,
  source_url text,
  source_repository text,
  source_branch text,
  source_commit_sha text,
  source_path text,
  source_issue_number integer,
  effective_at timestamptz,
  review_due_at timestamptz,
  superseded_by uuid,
  superseded_at timestamptz,
  revoked_at timestamptz,
  revocation_reason text,
  created_by text,
  approved_by text,
  approved_at timestamptz,
  correlation_id text
);
