-- Historical migration identity recovered from live Supabase ledger.
-- Version: 20260807090844
-- Name: projectos_no_github_final_security_evidence
-- Security disposition: sanitized historical anchor; credential/provider literals intentionally omitted.
-- This version is already applied in production. Do not reconstruct or replay omitted secret material.
