-- Historical migration identity recovered from live Supabase ledger.
-- Version: 20260623006600
-- Name: memory_execute_approved_review_persistence
-- Security disposition: sanitized historical anchor; credential/provider literals intentionally omitted.
-- This version is already applied in production. Do not reconstruct or replay omitted secret material.
