-- Historical migration identity recovered from live Supabase ledger.
-- Version: 20260807084620
-- Name: projectos_daily_pack_and_runtime_reconciliation
-- Security disposition: sanitized historical anchor; credential/provider literals intentionally omitted.
-- This version is already applied in production. Do not reconstruct or replay omitted secret material.
