-- Historical migration identity recovered from live Supabase ledger.
-- Version: 20260731111248
-- Name: posthog_product_intelligence
-- Security disposition: sanitized historical anchor; credential/provider literals intentionally omitted.
-- This version is already applied in production. Do not reconstruct or replay omitted secret material.
