-- Historical migration identity recovered from live Supabase ledger.
-- Version: 20260807085215
-- Name: projectos_bridge_v13_evidence_reconciliation
-- Security disposition: sanitized historical anchor; credential/provider literals intentionally omitted.
-- This version is already applied in production. Do not reconstruct or replay omitted secret material.
